### ISSUE TITLE
t.Setenv vs paralleltest

### ISSUE THREAD

**Issue by nasermirzaei89** [kunwardeep/paralleltest#13]
This library forces you to run parallel tests. But how can I test something that depends on environment variables?

Like this https://github.com/nasermirzaei89/env

**Comment by kunwardeep** [comment]
Hey @nasermirzaei89, unfortunately, I am not doing active development on this., but would be more than happy to have a look at a PR if you have one.

**Comment by kunwardeep** [comment]
Hey @nasermirzaei89, would you please be able to test the latest release and see if it solves your problem? We have just added a new flag -i which ignores missing calls to t.Parallel and only reports incorrect uses of it.

**Comment by nasermirzaei89** [comment]
Yep. it doesn't show any error with `-i` flag!

**Comment by kunwardeep** [comment]
Thanks, @nasermirzaei89 for testing this out. I hope this solves your problem.  I will now close this issue. 

Fixed in 1.0.6

**Comment by mitar** [comment]
`-i` does not really solve this. I would want missing calls to be reported, but only that it does not report it if you use `t.Setenv`.
